name: gmstrat
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - tqdm
  - networkx
  - matplotlib
  - plotly
  - geopandas
  - pyarrow
  - pytest
  - jupyterlab
